// "Ethereal whispers": short, in-character utterances from the pet. Generated by
// the local LLM when available, with a seeded template fallback so the pet always
// speaks in character even with no model running. Cooldown + cache keep it calm.

import { deriveGenome, makeRng, stageLabel, type Pet, type DimensionEventType } from '@yao/core';
import { config } from '../config.js';
import { OllamaProvider } from './ollama.js';
import type { InferenceProvider } from './client.js';
import { VOICES, voiceFor } from './voices.js';

const provider: InferenceProvider = new OllamaProvider(
  config.ollamaUrl,
  config.ollamaModel,
);

// Per-pet cooldown. Local inference is free, so this is short — just enough to
// avoid spamming the whisper log.
const COOLDOWN_MS = 45_000;
const lastWhisperAt = new Map<string, number>();

// Cache by (stage, moodBucket, event, personality): many states repeat.
const cache = new Map<string, string>();

export type WhisperSource = 'llm' | 'template';
export interface Whisper {
  text: string;
  source: WhisperSource;
}

function moodBucket(mood: number): 'low' | 'mid' | 'high' {
  return mood < 35 ? 'low' : mood > 70 ? 'high' : 'mid';
}

const CTX: Record<DimensionEventType, string> = {
  hatch: '你剛在次元中初次成形。',
  evolve: '你剛蛻為新的形態。',
  mood_drift: '一陣安靜的波動流過你。',
  interact: '飼主剛向你伸出手。',
};

function buildPrompt(pet: Pet, event: DimensionEventType): string {
  const stage = stageLabel(pet.stage);
  const m = moodBucket(pet.stats.mood);
  return `這隻生靈名為「${pet.name}」，當前為「${stage}」卷，心情${m}。${CTX[event]}\n依你的身份，吐出一句。`;
}

// Compose via 三分身: the avatar is chosen by event + day, then voiced by the
// local LLM (its system prompt) or its own seeded template pool as fallback.
async function compose(pet: Pet, event: DimensionEventType): Promise<Whisper> {
  const dayIndex = Math.floor(Date.now() / 86_400_000);
  const voice = voiceFor(event, dayIndex);
  const def = VOICES[voice];
  const key = `${voice}|${pet.stage}|${moodBucket(pet.stats.mood)}|${event}`;

  if (config.whisperEnabled) {
    const cached = cache.get(key);
    if (cached) return { text: cached, source: 'llm' };
    const text = await provider.generate(buildPrompt(pet, event), {
      system: def.system,
      maxTokens: 64,
    });
    if (text) {
      const clean = text.replace(/^["'「」\s]+|["'「」\s]+$/g, '').split('\n')[0] ?? text;
      cache.set(key, clean);
      return { text: clean, source: 'llm' };
    }
  }
  // Seeded fallback from this avatar's own template pool.
  const rng = makeRng(`${pet.seed}:${voice}:${event}:${Math.floor(Date.now() / 60000)}`);
  return { text: rng.pick(def.templates), source: 'template' };
}

/** Generate a whisper if the pet is off cooldown, else null. */
export async function maybeWhisper(
  pet: Pet,
  event: DimensionEventType,
): Promise<Whisper | null> {
  const now = Date.now();
  const last = lastWhisperAt.get(pet.id) ?? 0;
  // Significant events (hatch/evolve) always speak; ambient ones respect cooldown.
  const forced = event === 'hatch' || event === 'evolve';
  if (!forced && now - last < COOLDOWN_MS) return null;
  lastWhisperAt.set(pet.id, now);
  return compose(pet, event);
}

/** Suggest a name for a newborn pet (LLM if available, else seeded fallback). */
export async function generateName(seed: string): Promise<string> {
  const genome = deriveGenome(seed);
  if (config.whisperEnabled) {
    const text = await provider.generate(
      `Invent a single short, ethereal, otherworldly name (1-2 words, no explanation) for a ${genome.personality} spirit creature with ${genome.bodyForm} form. Output only the name.`,
      { system: 'You name ethereal dimensional creatures. Reply with only the name.', maxTokens: 12, temperature: 1 },
    );
    if (text) {
      const name = text.replace(/^["'\s]+|["'.\s]+$/g, '').split('\n')[0]?.slice(0, 24);
      if (name) return name;
    }
  }
  // Seeded fallback name from syllable pools.
  const rng = makeRng(seed + ':name');
  const a = ['Ny', 'Ae', 'Lu', 'Vyr', 'Sol', 'Mi', 'Zha', 'Ori', 'Tha', 'El'];
  const b = ['ra', 'lis', 'wen', 'mora', 'sha', 'lae', 'ven', 'ira', 'oth', 'une'];
  return rng.pick(a) + rng.pick(b);
}

export const whisperProvider = provider;
