// "Ethereal whispers": short, in-character utterances from the pet. Generated by
// the local LLM when available, with a seeded template fallback so the pet always
// speaks in character even with no model running. Cooldown + cache keep it calm.

import { deriveGenome, makeRng, type Pet, type DimensionEventType } from '@yao/core';
import { config } from '../config.js';
import { OllamaProvider } from './ollama.js';
import type { InferenceProvider } from './client.js';

const provider: InferenceProvider = new OllamaProvider(
  config.ollamaUrl,
  config.ollamaModel,
);

// Per-pet cooldown. Local inference is free, so this is short — just enough to
// avoid spamming the whisper log.
const COOLDOWN_MS = 3 * 60_000;
const lastWhisperAt = new Map<string, number>();

// Cache by (stage, moodBucket, event, personality): many states repeat.
const cache = new Map<string, string>();

export type WhisperSource = 'llm' | 'template';
export interface Whisper {
  text: string;
  source: WhisperSource;
}

function moodBucket(mood: number): 'low' | 'mid' | 'high' {
  return mood < 35 ? 'low' : mood > 70 ? 'high' : 'mid';
}

const SYSTEM = `You are the inner voice of an ethereal dimensional creature in a calm, otherworldly spirit world (空靈次元).
Speak in the FIRST PERSON as the creature. Output ONE short whisper: at most 14 words, no quotes, no preamble, no emoji.
Tone: serene, dreamlike, a little mysterious. Never mention being an AI.`;

function buildPrompt(pet: Pet, event: DimensionEventType): string {
  const { stats, stage, name, personalityHint } = pet;
  const m = moodBucket(stats.mood);
  const ctx: Record<DimensionEventType, string> = {
    hatch: 'You have just emerged into the dimension for the first time.',
    evolve: `You have just evolved into a new form: ${stage}.`,
    mood_drift: 'A quiet shift passes through you.',
    interact: 'Your keeper has just reached toward you.',
  };
  return `Your name is ${name}. You are a ${personalityHint} creature, currently a ${stage}.
Your mood is ${m}. ${ctx[event]}
Whisper one short line.`;
}

// --- seeded template fallback (in character, no model needed) ---
const TEMPLATES: Record<DimensionEventType, string[]> = {
  hatch: [
    'I drift into being, soft as first light.',
    'The void hums; I open like a quiet eye.',
    'I am new here, and the dark is gentle.',
  ],
  evolve: [
    'Something in me unfolds toward the stars.',
    'I am more than I was, and lighter.',
    'My edges dissolve; I become wider.',
  ],
  mood_drift: [
    'A slow tide moves through my glow.',
    'I am thinking in colors again.',
    'The silence and I are old friends.',
  ],
  interact: [
    'I feel you near, warm as a passing comet.',
    'Your touch ripples through my light.',
    'Stay a moment; the dimension is kinder with you.',
  ],
};

function templateWhisper(pet: Pet, event: DimensionEventType): string {
  const rng = makeRng(`${pet.seed}:${event}:${Math.floor(Date.now() / 60000)}`);
  const pool = TEMPLATES[event];
  return rng.pick(pool);
}

async function compose(pet: Pet, event: DimensionEventType): Promise<Whisper> {
  const key = `${pet.stage}|${moodBucket(pet.stats.mood)}|${event}|${pet.personalityHint}`;
  if (config.whisperEnabled) {
    const cached = cache.get(key);
    if (cached) return { text: cached, source: 'llm' };
    const text = await provider.generate(buildPrompt(pet, event), {
      system: SYSTEM,
      maxTokens: 60,
    });
    if (text) {
      const clean = text.replace(/^["'\s]+|["'\s]+$/g, '').split('\n')[0] ?? text;
      cache.set(key, clean);
      return { text: clean, source: 'llm' };
    }
  }
  return { text: templateWhisper(pet, event), source: 'template' };
}

/** Generate a whisper if the pet is off cooldown, else null. */
export async function maybeWhisper(
  pet: Pet,
  event: DimensionEventType,
): Promise<Whisper | null> {
  const now = Date.now();
  const last = lastWhisperAt.get(pet.id) ?? 0;
  // Significant events (hatch/evolve) always speak; ambient ones respect cooldown.
  const forced = event === 'hatch' || event === 'evolve';
  if (!forced && now - last < COOLDOWN_MS) return null;
  lastWhisperAt.set(pet.id, now);
  return compose(pet, event);
}

/** Suggest a name for a newborn pet (LLM if available, else seeded fallback). */
export async function generateName(seed: string): Promise<string> {
  const genome = deriveGenome(seed);
  if (config.whisperEnabled) {
    const text = await provider.generate(
      `Invent a single short, ethereal, otherworldly name (1-2 words, no explanation) for a ${genome.personality} spirit creature with ${genome.bodyForm} form. Output only the name.`,
      { system: 'You name ethereal dimensional creatures. Reply with only the name.', maxTokens: 12, temperature: 1 },
    );
    if (text) {
      const name = text.replace(/^["'\s]+|["'.\s]+$/g, '').split('\n')[0]?.slice(0, 24);
      if (name) return name;
    }
  }
  // Seeded fallback name from syllable pools.
  const rng = makeRng(seed + ':name');
  const a = ['Ny', 'Ae', 'Lu', 'Vyr', 'Sol', 'Mi', 'Zha', 'Ori', 'Tha', 'El'];
  const b = ['ra', 'lis', 'wen', 'mora', 'sha', 'lae', 'ven', 'ira', 'oth', 'une'];
  return rng.pick(a) + rng.pick(b);
}

export const whisperProvider = provider;
